services:
  postgres:
    image: postgres:15
    container_name: gator_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  goose:
    container_name: gator_goose
    build:
      context: goose
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./sql/schema/:${GOOSE_MIGRATION_DIR}

volumes:
  postgres_data:
